Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  # Копируем пустой файл
  config.vm.provision "file", source: "empty_file.txt", destination: "/home/vagrant/empty_file.txt"

  # Provisioning
  config.vm.provision "shell", privileged: true, inline: <<-SHELL
    apt-get update

    # Python + pip
    apt-get install -y python3 python3-pip python3-setuptools python3-wheel

    # Обновляем pip
    python3 -m pip install --upgrade pip setuptools wheel

    # Ставим библиотеки (ТОЛЬКО бинарник)
    python3 -m pip install --only-binary=:all: django psycopg2-binary
  SHELL
end
